version: '3'

services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db

  go-service:
    build: ./go_server
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - python_service
      - node_service

  python_service:
    build: ./python_order_service
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  node_service:
    build: ./node_receipt_service
    ports:
      - "3000:3000"
    depends_on:
      - mongo
